### ISSUE TITLE
Add task creation and tracking

### ISSUE THREAD

**Issue by opny721** [SporosDAO/sweat-token#11]
- [x] Setup flow contrib and project manager roles
- [x] Create UI interfaces as per [Figma](https://www.figma.com/file/4V3DBa9tF69vo1DWkR3jpB/SweatTokenV2?node-id=0%3A1)
- [x] Define models and create APIs to interact with backend

**Comment by opny721** [comment]
Added #38 and #39 to split up workload
